### ISSUE TITLE
Black background when opening the Dimelo view after receiving a notification

### ISSUE THREAD

**Issue by avezier** [dimelo/Dimelo-iOS#10]
When the app is running in foreground and I open the Dimelo view, the UI of the Dimelo view is correct:

```objective-c
Dimelo.sharedInstance().displayChatView()
```
```objective-c
   func dimeloDisplayChatViewController(_ dimelo: Dimelo!) {
        if let dimeloVC = dimelo.chatViewController() {
            dimeloVC.navigationItem.rightBarButtonItem = UIBarButtonItem(barButtonSystemItem: .done, target: self, action: #selector(closeChat))
            dimeloVC.navigationItem.rightBarButtonItem?.tintColor = UIColor.black
            AppDelegate.shared.window?.rootViewController?.present(dimeloVC, animated: true, completion: nil)
        }
    }
```

However when I display the Dimelo view from the `didReceiveNotification` callback, the background of the view is black, as in the attached screenshot

![bugui](https://user-images.githubusercontent.com/4671676/27630580-3bb7032e-5bf6-11e7-8819-4039e6b62078.jpg)

**Comment by jarthod** [comment]
Thanks for reporting this, this issue has already been reported and fixed in `1.5.1` (https://github.com/dimelo/Dimelo-iOS/blob/7f2663c209d841c4bddb05a74c036b3696071051/CHANGELOG.md#dimelo-ios-sdk-151-december-9th-2016)
I saw in your other issue that you're using `1.5.0`, please upgrade to the latest version (`1.7.1`)
