### ISSUE TITLE
Push notifications unexpected behaviour

### ISSUE THREAD

**Issue by leonovvalentin** [dimelo/Dimelo-iOS#17]
Hello!

We encountered such unexpected behaviour. If we register to Dimelo from two different devices, push notifications is pushed to only last of them (device which was second registered to Dimelo).

Thanks.

**Comment by jarthod** [comment]
Hello!

Yes indeed, this is the expected behavior, to prevent any privacy issue where a user could receive notifications on someone else's device or a shared one after a short use. If you want to try the notifications on multiple devices at the same time, you need to register with different user identifiers.

**Comment by leonovvalentin** [comment]
Thank you for the clarification!
